#!/usr/bin/env python3
"""Programmatic CLI reference documentation generator (P9-02).

Inspects the Typer application in `vhecfsck.cli` and generates
`docs/cli-reference.md`.
"""

from __future__ import annotations

from pathlib import Path

from typer.main import get_command
from vhecfsck.cli import app

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "cli-reference.md"


def generate_cli_docs() -> str:
    click_app = get_command(app)
    lines: list[str] = [
        "# CLI Reference",
        "",
        "> **Note**: This document is **programmatically generated** from the Typer CLI application.",
        "> Do not edit this file by hand.",
        "",
        "## Overview",
        "",
        f"```\n{click_app.help or 'vhecfsck CLI'}\n```",
        "",
        "## Exit Codes",
        "",
        "| Exit Code | Name | Description |",
        "| :---: | :--- | :--- |",
        "| `0` | `OK` | Audit completed cleanly; all metrics pass. |",
        "| `1` | `WARN` | Audit completed with warning threshold breaches. |",
        "| `2` | `FAIL` | Audit completed with failure threshold breaches. |",
        "| `3` | `INCONCLUSIVE` | Audit inconclusive (missing capability or sample size). |",
        "| `4` | `USAGE` | Invalid arguments, connection loss, or resource ceiling exceeded. |",
        "| `70` | `INTERNAL` | Unhandled internal engine failure. |",
        "",
        "## Global Options",
        "",
        "| Option | Type | Default | Description |",
        "| :--- | :--- | :--- | :--- |",
    ]

    for param in click_app.params:
        opts = ", ".join(f"`{opt}`" for opt in param.opts)
        if param.secondary_opts:
            opts += ", " + ", ".join(f"`{opt}`" for opt in param.secondary_opts)
        type_name = str(param.type)
        if hasattr(param.type, "name"):
            type_name = param.type.name
        default_val = str(param.default) if param.default is not None else "None"
        help_text = (param.help or "").replace("\n", " ").strip()
        lines.append(f"| {opts} | `{type_name}` | `{default_val}` | {help_text} |")

    lines.extend(
        [
            "",
            "## Commands",
            "",
        ]
    )

    for cmd_name, cmd in sorted(click_app.commands.items()):
        lines.append(f"### `vhecfsck {cmd_name}`")
        lines.append("")
        if cmd.help:
            lines.append(cmd.help.strip())
            lines.append("")

        lines.append("#### Usage")
        lines.append("")
        lines.append("```bash")
        lines.append(f"vhecfsck {cmd_name} [OPTIONS]")
        lines.append("```")
        lines.append("")

        if cmd.params:
            lines.append("#### Options")
            lines.append("")
            lines.append("| Option | Type | Default | Description |")
            lines.append("| :--- | :--- | :--- | :--- |")
            for param in cmd.params:
                opts = ", ".join(f"`{opt}`" for opt in param.opts)
                if param.secondary_opts:
                    opts += ", " + ", ".join(f"`{opt}`" for opt in param.secondary_opts)
                type_name = str(param.type)
                if hasattr(param.type, "name"):
                    type_name = param.type.name
                default_val = (
                    str(param.default) if param.default is not None else "None"
                )
                help_text = (param.help or "").replace("\n", " ").strip()
                lines.append(
                    f"| {opts} | `{type_name}` | `{default_val}` | {help_text} |"
                )
            lines.append("")

        if hasattr(cmd, "commands") and cmd.commands:
            for sub_name, sub_cmd in sorted(cmd.commands.items()):
                lines.append(f"#### Subcommand `vhecfsck {cmd_name} {sub_name}`")
                lines.append("")
                if sub_cmd.help:
                    lines.append(sub_cmd.help.strip())
                    lines.append("")
                if sub_cmd.params:
                    lines.append("| Option | Type | Default | Description |")
                    lines.append("| :--- | :--- | :--- | :--- |")
                    for param in sub_cmd.params:
                        opts = ", ".join(f"`{opt}`" for opt in param.opts)
                        if param.secondary_opts:
                            opts += ", " + ", ".join(
                                f"`{opt}`" for opt in param.secondary_opts
                            )
                        type_name = str(param.type)
                        if hasattr(param.type, "name"):
                            type_name = param.type.name
                        default_val = (
                            str(param.default) if param.default is not None else "None"
                        )
                        help_text = (param.help or "").replace("\n", " ").strip()
                        lines.append(
                            f"| {opts} | `{type_name}` | `{default_val}` | {help_text} |"
                        )
                    lines.append("")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import subprocess

    content = generate_cli_docs()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    subprocess.run(["uv", "run", "ruff", "format", str(OUTPUT_PATH)], check=False)
    print(f"Successfully generated {OUTPUT_PATH}")
