#!/usr/bin/env python3
"""Programmatic Report schema reference documentation generator (P9-02).

Inspects the Pydantic `Report` model (`generate_report_schema()`) and generates
`docs/schema-reference.md`.
"""

from __future__ import annotations

import json
from pathlib import Path

from vhecfsck.report.json_report import generate_report_schema

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "schema-reference.md"


def generate_schema_docs() -> str:
    schema = generate_report_schema()
    defs = schema.get("$defs", {})

    lines: list[str] = [
        "# Report Schema Reference",
        "",
        "> **Note**: This document is **programmatically generated** from the Pydantic `Report` v1.1 model.",
        "> Do not edit this file by hand.",
        "",
        "## Overview",
        "",
        "The `vhecfsck` audit report JSON schema follows SemVer versioning (current version: `1.1`).",
        "It provides machine-readable diagnostic output for CI/CD pipelines, Prometheus exporters, and 3D visualizer clients.",
        "",
        "```json",
        f'"$schema": "{schema.get("$schema", "http://json-schema.org/draft-07/schema#")}"',
        f'"title": "{schema.get("title", "Report")}"',
        "```",
        "",
        "## Model Definitions",
        "",
    ]

    for def_name, def_data in sorted(defs.items()):
        lines.append(f"### `{def_name}`")
        lines.append("")
        desc = def_data.get("description", "").strip()
        if desc:
            lines.append(desc)
            lines.append("")

        if "enum" in def_data:
            lines.append("**Enumeration Values:**")
            lines.append("")
            for enum_val in def_data["enum"]:
                lines.append(f"- `{enum_val}`")
            lines.append("")

        props = def_data.get("properties", {})
        if props:
            lines.append("| Field | Type | Description |")
            lines.append("| :--- | :--- | :--- |")
            required_set = set(def_data.get("required", []))
            for prop_name, prop_data in props.items():
                prop_type = prop_data.get("type", "")
                if not prop_type and "anyOf" in prop_data:
                    types = [
                        t.get("type", "object")
                        for t in prop_data["anyOf"]
                        if "type" in t
                    ]
                    prop_type = " | ".join(types) if types else "any"
                if not prop_type and "$ref" in prop_data:
                    prop_type = f"[`{prop_data['$ref'].split('/')[-1]}`](#{prop_data['$ref'].split('/')[-1].lower()})"
                req_suffix = " *(required)*" if prop_name in required_set else ""
                prop_desc = (
                    prop_data.get("description", prop_data.get("title", ""))
                    .replace("\n", " ")
                    .strip()
                )
                lines.append(
                    f"| `{prop_name}`{req_suffix} | `{prop_type}` | {prop_desc} |"
                )
            lines.append("")

    lines.extend(
        [
            "## Full JSON Schema Raw Dump",
            "",
            "```json",
            json.dumps(schema, indent=2, ensure_ascii=False),
            "```",
            "",
        ]
    )

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import subprocess

    content = generate_schema_docs()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    subprocess.run(["uv", "run", "ruff", "format", str(OUTPUT_PATH)], check=False)
    print(f"Successfully generated {OUTPUT_PATH}")
